name: netease_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  # 轮播图
  flutter_swiper: ^1.1.6
  # 状态管理
  provider: ^3.1.0
  # 屏幕尺寸计算工具
  flutter_screenutil: ^0.5.3
  # http请求库
  dio: ^3.0.0
  # 音频播放
  audioplayer: ^0.5.2
  # 视频播放
  video_player: ^0.10.2
 
  json_annotation: ^3.0.0

  json_serializable: ^3.2.3

  build_runner: ^1.7.1

dev_dependencies:


flutter:

  uses-material-design: true

  assets:
    - assets/images/login_bg.jpg
    - assets/images/theme.jpeg
    - assets/images/bg_blur.jpeg
    - assets/images/song_cover_default.jpeg

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
