name: netease_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_swiper: ^1.1.6

  flutter_screenutil: ^0.5.3

  dio: ^3.0.0

dev_dependencies:


flutter:

  uses-material-design: true

  assets:
    - assets/images/login_bg.jpg
    - assets/images/theme.jpeg

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
